# Generated by Django 5.2.17 on 2026-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('type', models.CharField(choices=[('STOCK_IN', 'STOCK_IN'), ('STOCK_OUT', 'STOCK_OUT'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('TRANSFER_IN', 'TRANSFER_IN'), ('ADJUSTMENT_IN', 'ADJUSTMENT_IN'), ('ADJUSTMENT_OUT', 'ADJUSTMENT_OUT'), ('RETURN', 'RETURN'), ('DAMAGE', 'DAMAGE'), ('REVERSAL', 'REVERSAL')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', 'warehouse_id', 'created_at'], name='inventory_s_product_b98636_idx')],
            },
        ),
    ]
