# Generated by Django 5.2.17 on 2026-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True)),
                ('from_warehouse_id', models.IntegerField()),
                ('to_warehouse_id', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('REQUESTED', 'REQUESTED'), ('APPROVED', 'APPROVED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('RECEIVED', 'RECEIVED'), ('CANCELLED', 'CANCELLED')], default='DRAFT', max_length=20)),
                ('requested_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product_id', 'warehouse_id'), name='unique_product_warehouse_inventory'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
    ]
