# Generated by Django 5.2.17 on 2026-09-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
